services:
  mysql:
    image: mysql:8.0
    container_name: mysql-shared
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: "tmdnlvm7!"
      MYSQL_USER: pinggyewang_user
      MYSQL_PASSWORD: tmdnlvm7!

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--max_connections=200',
      '--innodb_buffer_pool_size=512M'
    ]

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 30s

    networks:
      - pinggyeking-network

volumes:
  mysql_data:

networks:
  pinggyeking-network:
    driver: bridge
    name: pinggyeking-network