services:
  spring-app:
    container_name: spring-app-prod

    ports:
      - "8081:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pinggyewang_prod?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=tmdnlvm7!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - LOGGING_LEVEL_ROOT=WARN
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC

    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s