version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: pinggyewang_dev
      MYSQL_USER: pinggyewang_user
      MYSQL_PASSWORD: pinggyewang_pass

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  spring-app:
    build: .                            # Dockerfile을 사용해서 빌드
    container_name: spring-app

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/pinggyewang_dev?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

volumes:
  mysql_data: