spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinggyewang_dev?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 운영환경에서는 validate 또는 none 사용 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

clova:
  api:
    url: https://clovastudio.stream.ntruss.com/testapp/v3/chat-completions/HCX-005
    key: nv-d6eadc1a642f46d2834ffdb0c1e11e07flHE

server:
  address: 0.0.0.0
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /