spring:
  datasource:
    url: jdbc:mysql://mysql:3306/pinggyewang_dev?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: tmdnlvm7!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

clova:
  api:
    url: https://clovastudio.stream.ntruss.com/testapp/v3/chat-completions/HCX-005
    key: nv-d6eadc1a642f46d2834ffdb0c1e11e07flHE