spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false

logging:
  level:
    org.springframework.security: DEBUG

clova:
  api:
    url: https://clovastudio.stream.ntruss.com/testapp/v3/chat-completions/HCX-005
    key: nv-d6eadc1a642f46d2834ffdb0c1e11e07flHE

server:
  port: 8080