spring:
  datasource:
    url: jdbc:mysql://db-35uo47-kr.vpc-pub-cdb.ntruss.com:3306/pinggyewang_dev?useSSL=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: swyp
    password: tmdnlvm7!

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # 운영환경에서는 기존 데이터 유지하며 스키마 업데이트
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.swyp10.pinggyewang: INFO
    org.springframework.security: WARN

clova:
  api:
    url: YOUR_PROD_CLOVA_URL
    key: YOUR_PROD_CLOVA_KEY

server:
  port: 8080