spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinggyewang?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pinggyewang_user
    password: your_secure_password

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.swyp10.pinggyewang: INFO
    org.springframework.security: WARN

clova:
  api:
    url: YOUR_PROD_CLOVA_URL
    key: YOUR_PROD_CLOVA_KEY

server:
  port: 8080