name: CD to NCP Instance

on:
  push:
    branches: [ dev, feature-ai ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon

      - name: Rename artifact to app.jar
        run: cp build/libs/pinggye-wang-0.0.1-SNAPSHOT.jar app.jar

      - name: Verify artifact
        run: ls -lh app.jar

      # SSH 에이전트 설정 (키 등록)
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.NCP_USER }}@${{ secrets.NCP_HOST }} \
          "sudo mkdir -p /root/app && sudo chown ${{ secrets.NCP_USER }} /root/app"

          scp -o StrictHostKeyChecking=no \
          app.jar \
          docker-compose.yml \
          docker-compose.dev.yml \
          Dockerfile \
          scripts/deploy.sh \
          ${{ secrets.NCP_USER }}@${{ secrets.NCP_HOST }}:/root/app/

      - name: Deploy on NCP
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            cd /root/app
            chmod +x deploy.sh
            ./deploy.sh
