name: CD to NCP Instance

on:
  push:
    branches: [ dev, feature-ai ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon

      - name: Verify artifact
        run: ls -lh build/libs

      # SSH 에이전트 설정 (키 등록)
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 1) JAR 파일 복사 (scp-action)
      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host:     ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     22
          file_glob: true
          source:   "build/libs/*.jar"
          target:   "/root/app/"

      # 2) 배포 스크립트 실행 (ssh-action)
      - name: Deploy on NCP
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:     ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          port:     22
          script: |
            cd /root/app
            chmod +x deploy.sh
            ./deploy.sh